### ISSUE TITLE
initial django application and project skeleton (~1h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/django-crs#1]
Just follow the [tutorial](https://docs.djangoproject.com/) steps for using `django-admin` to create an initial project and application.

Let's agree on the following project structure:
```
/README.md
/django-crs # <<< this is the project generated by django-admin createproject (or something along those lines)
/django-crs/crs    #   <<< this is the application generated by django-admin startapp or something along those lines
/manage.py # this is generated by django-admin createproject I think
...

Note that your `/django-crs/settings.py` should include `crs` in the `INCLUDED_APPLICATIONS` variable
```

**Comment by shadiakiki1986** [comment]
I noticed that this is done, but also you commited `db.sqlite3` file, which is the database file.

Repositories are only for source code, and not the database.

In some cases, this could be a serious confidentiality breach if you're working on a bank's dataset that contains client names and contact info.

I think you will need `solution 5` from [here](https://stackoverflow.com/a/23188613/4126114)

**Comment by RaedZorkot** [comment]
I fixed the mistake. The database file is removed.
