### ISSUE TITLE
create django models based on the CRS schema (~15h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/django-crs#2]
General
- [CRS](https://www.oecd.org/tax/automatic-exchange/common-reporting-standard/schema-and-user-guide/) is a tax reporting requirement similar to [FATCA](https://en.wikipedia.org/wiki/Foreign_Account_Tax_Compliance_Act) but for all countries instead of just USA
- this project is about generating django models that mirror the CRS XML schema
- the CRS schema documents which data is supposed to be sent by institutions to countries participating in CRS
- it will facilitate financial institutions to prepare their client tax data submission
    - the most similar project is the FATCA-equivalent [fatca-ides-php](https://github.com/teamshadi/fatca-ides-php)

Steps
- download the [CRS XML Schema](https://www.oecd.org/tax/automatic-exchange/common-reporting-standard/schema-and-user-guide/CRS-schema-v1.0.zip)
- use [xsd_to_django_models](https://github.com/tuffnatty/xsd_to_django_model) to create django models from the CRS XML schema
- write up a [django management command](https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/) that populates the database using the models generated above with example accounts, account balances, names, etc to demonstrate usage

**Comment by shadiakiki1986** [comment]
Edit: I edited the issue description and split out the steps more clearly. @RaedZorkot let me know if anything is still unclear

**Comment by RaedZorkot** [comment]
Update: Added two django command to populate and clear the temporary models with random examples and display them in a table on /crs/. Still having difficulties using the [xsd_to_django_models](https://github.com/tuffnatty/xsd_to_django_model) to create the CRS models.

**Comment by shadiakiki1986** [comment]
I see that you wrote your own models to get the management commands to work. Let me know if you need help with the `xsd_to_django_models` package

**Comment by RaedZorkot** [comment]
Update: I met yesterday with Jad and we found out that the module xsd_to_django_models is not compatible with the xsd files we have. However I have found another module that is called generateDS, which works really well and I was able to convert the xsd files into django models. I have updated the django-crs app and commited the changes. 
I still have to do the commands to populate the database.
